/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package datadaycare;
import java.io.File;
import java.io.FileWriter;
import javax.swing.JOptionPane;
import javax.swing.DefaultListModel;
import java.util.Date;
import java.util.regex.Pattern;
import java.text.SimpleDateFormat;

/**
 *
 * @author lastp
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtGName = new javax.swing.JTextField();
        txtGSurname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cboGenderG = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cboDayOld = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cboMonthOld = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        cboGYearB = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSaveInformation = new javax.swing.JButton();
        rbParent = new javax.swing.JRadioButton();
        rbGuardian = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        rbGood = new javax.swing.JRadioButton();
        rbAverage = new javax.swing.JRadioButton();
        rbBad = new javax.swing.JRadioButton();
        ResidentialAddress = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        txtEmergency = new javax.swing.JTextField();
        txtContact1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        txtChildName = new javax.swing.JTextField();
        txtChildSurname = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        cboGenderC = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        cboCDayB = new javax.swing.JComboBox<>();
        jLabel34 = new javax.swing.JLabel();
        cboCMonthB = new javax.swing.JComboBox<>();
        jLabel35 = new javax.swing.JLabel();
        cboCYearB = new javax.swing.JComboBox<>();
        lblOutput = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Guardian = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstKids = new javax.swing.JList<>();
        lblCreate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Day Care Data");

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));
        jPanel1.setMaximumSize(new java.awt.Dimension(438, 253));

        jLabel1.setText("Name: ");

        jLabel2.setText("Surname: ");

        jLabel4.setText("Gender: ");

        cboGenderG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Male", "Female" }));

        jLabel8.setText("__ Date Of Birth __");

        jLabel9.setText("Day: ");

        cboDayOld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel10.setText("Month: ");

        cboMonthOld.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel11.setText("Year: ");

        cboGYearB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1950", "1951", "1952", "1953", "1954", "1955", "1956", "1957", "1958", "1959", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021", "2022", " " }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboDayOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboMonthOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboGYearB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 10, Short.MAX_VALUE))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cboDayOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(cboMonthOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(cboGYearB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel37.setText("Parental Or Guardian:");

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSaveInformation.setText("Save Information To Text File");
        btnSaveInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveInformationActionPerformed(evt);
            }
        });

        rbParent.setText("Parent");
        rbParent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbParentActionPerformed(evt);
            }
        });

        rbGuardian.setText("Guardian");
        rbGuardian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGuardianActionPerformed(evt);
            }
        });

        jLabel6.setText("RelationShip With The Child:");

        rbGood.setText("Good");
        rbGood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbGoodActionPerformed(evt);
            }
        });

        rbAverage.setText("Average");
        rbAverage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbAverageActionPerformed(evt);
            }
        });

        rbBad.setText("Bad");
        rbBad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbBadActionPerformed(evt);
            }
        });

        ResidentialAddress.setText("Residential Address:");

        jLabel7.setText("Contact Detials: ");

        jLabel12.setText("Emergency Contact Detials: ");

        txtContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtContactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel37)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtGSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cboGenderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbParent, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbGuardian, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSaveInformation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ResidentialAddress)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAddress))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(rbGood)
                                .addGap(18, 18, 18)
                                .addComponent(rbAverage, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(rbBad)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtEmergency))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtContact)
                                    .addComponent(txtContact1))))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtGName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtGSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cboGenderG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(jLabel37)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbParent)
                    .addComponent(rbGuardian))
                .addGap(7, 7, 7)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(rbGood)
                    .addComponent(rbAverage)
                    .addComponent(rbBad))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ResidentialAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtContact1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtEmergency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSaveInformation)
                    .addComponent(btnClear))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 51, 255), 1, true));
        jPanel2.setMaximumSize(new java.awt.Dimension(438, 253));

        jLabel25.setText("Name: ");

        jLabel26.setText("Surname: ");

        jLabel27.setText("Gender: ");

        cboGenderC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "...", "Male", "Female" }));

        jLabel32.setText("__ Date Of Birth __");

        jLabel33.setText("Day: ");

        cboCDayB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        jLabel34.setText("Month: ");

        cboCMonthB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));

        jLabel35.setText("Year: ");

        cboCYearB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022" }));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCDayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel34)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCMonthB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cboCYearB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(cboCDayB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel34)
                    .addComponent(cboCMonthB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel35)
                    .addComponent(cboCYearB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel5.setText("Enrollment Date: ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cboGenderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtChildName, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtChildSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblOutput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtChildName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtChildSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(cboGenderC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOutput)
                    .addComponent(jLabel5))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        Guardian.setText("Guardian");

        jLabel3.setText("Student");

        jScrollPane1.setViewportView(lstKids);

        lblCreate.setText("File has not been saved yet. When you have added all information press save\n");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3)
                    .addComponent(Guardian)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Guardian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

DefaultListModel<String> dlmList = new DefaultListModel<>();
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Sets check variable
        String strNKR;
        strNKR = "";
        Boolean boolCheck=true;
        String strAddress="",strContact="",strContact2="",strEmergency="";       
        strAddress = txtAddress.getText();
        strContact = txtContact.getText();
        strEmergency = txtEmergency.getText();
        int intLength2 = strEmergency.length();
        int intLength = strContact.length();
               
       
        //removes all data in dlmList
        dlmList.removeAllElements();
        
        //Day of enrollment
        Date dtDate = new Date();       
        SimpleDateFormat sdfTimeFormat = new SimpleDateFormat("dd MMMM yyyy");
        String strEnrolment = sdfTimeFormat.format(dtDate);
        
        //Child Name and surname variables
        String strCName, strCSurName;
        
        //Guardian Name and Surname variables
        String strGName, strGSurName;
        
        //Child Birthday Values strBDay is all 3 variables together
        String strBirthDay, strBirthMonth,strBDay, strBirthYear ;
        
        //This is the Guardians BirthDay Variables strGBday is the Full collection of the 3 variables together
        String strGBirthDay,  strGBirthMonth, strGBirthYear, strGBDay;
        //Gender variable information is being collected
        String strCGender = cboGenderC.getSelectedItem().toString();
        String strGGender = cboGenderG.getSelectedItem().toString();
        
        //Child Name and Surname is extracted    
        strCName = txtChildName.getText();
        strCSurName = txtChildSurname.getText();
        //Guardian Name and Surname extracted
        strGName = txtGName.getText();
        strGSurName = txtGSurname.getText();
        //Child Birthday information is extracted
        strBirthYear = cboCYearB.getSelectedItem().toString();
        strBirthDay = cboCDayB.getSelectedItem().toString();
        strBirthMonth = cboCMonthB.getSelectedItem().toString();
        //Guardian Birthday information is extracted
        strGBirthYear = cboGYearB.getSelectedItem().toString();
        strGBirthDay = cboDayOld.getSelectedItem().toString();
        strGBirthMonth = cboMonthOld.getSelectedItem().toString();
        //Child Bday variable being used
        strBDay = strBirthDay + " " + strBirthMonth + " " + strBirthYear;
        //Guardian Bday variable being used
        strGBDay = strGBirthDay + " " + strGBirthMonth + " "+ strGBirthYear;
   
    switch(strBirthYear){
        case"2022":
        {
          strNKR =  "New Born";
          break;
        }
        case"2021":
        {
          strNKR =  "KinderGarten";
          break;
        }
        case"2020":
        {
          strNKR =  "KinderGarten";
          break;
        }
        case"2019":
        {
          strNKR =  "KinderGarten";
          break;
        }
        case"2018":
        {
          strNKR =  "KinderGarten";
          break;
        }
        case"2017":
        {
          strNKR =  "Grade-R";
          break;
        }  
    }    
       String strGorP=""; 
       if(rbGuardian.isSelected())
      {          
      strGorP = "Guardian";
      }
       else if(rbParent.isSelected())
                { 
      strGorP = "Parent";
                }
        
        
        String strRelation="";
         if(rbGood.isSelected())
      {          
      strRelation = " is good";
      }
       else if(rbAverage.isSelected())
                {
      strRelation = " is Average";  
                }
         else if(rbBad.isSelected())
                {
      strRelation = " is bad";  
                }
        
         
         
    //Check if All information is filled in
        if("".equals(strCName))
        { JOptionPane.showMessageDialog(null, "Please Enter Child Name");
        boolCheck = false;
        }else if("".equals(strCSurName))
        { JOptionPane.showMessageDialog(null, "Please Enter Child Surname");
        boolCheck = false;
        }else if("...".equals(strCGender))
        { JOptionPane.showMessageDialog(null, "Please select a valid gender for the child");
        boolCheck = false;
        }else if("".equals(strGName))
        { JOptionPane.showMessageDialog(null, "Please Enter Guardian Name");
        boolCheck = false;
        }else if("".equals(strGSurName))
        { JOptionPane.showMessageDialog(null, "Please Enter Guardian Surname");
        boolCheck = false;
        } else if("...".equals(strGGender))
        { JOptionPane.showMessageDialog(null, "Please select a valid gender for the guardian");
        boolCheck = false;
        } else if("".equals(strRelation))
        { JOptionPane.showMessageDialog(null, "Please Enter Relationship status");
        boolCheck = false;
        }else if("".equals(strGorP))
        { JOptionPane.showMessageDialog(null, "Please Enter status of Guardian or Parent");
        boolCheck = false;
        }else if("".equals(strAddress))
        { JOptionPane.showMessageDialog(null, "Please Enter an Address");
        boolCheck = false;
        } else if("".equals(strContact))
        { JOptionPane.showMessageDialog(null, "Please Enter Contact Detials");
        boolCheck = false;
        }else if("".equals(strEmergency))
        { JOptionPane.showMessageDialog(null, "Please fill out emergency Contact details");
        boolCheck = false;
        }else if(10 != (intLength))
        {
            JOptionPane.showMessageDialog(null,"Please ensure that the Contact number is 10 digits long");
            boolCheck = false;
        }else if (Pattern.matches(".*[a-zA-Z]+.*",strContact))
        {
            JOptionPane.showMessageDialog(null,"Please only input numbers when filling in the contact information");
            boolCheck = false;
        }else if(10 != (intLength2))
            {
                JOptionPane.showMessageDialog(null,"Please ensure that the Emergency Contact number is 10 digits long");
                boolCheck = false;
            }else if (Pattern.matches(".*[a-zA-Z]+.*",strEmergency)) {
                boolCheck = false;
                JOptionPane.showMessageDialog(null,"Please only input numbers when filling in Emergency contact information");
            } 
        
    //Array is created for dlmList to add information    
     String[] arrContents = new String[19];       
       if (boolCheck == true)
       {
             if(rbGuardian.isSelected()){          
                dlmList.addElement("This Student Has A Guardian by the Name Of: " + strGName +" "+ strGSurName);
                dlmList.addElement("");
                                        }
             
             else if(rbParent.isSelected()){
                dlmList.addElement("This Student Has A Parent by the Name Of: " + strGName + " "+ strGSurName);
                dlmList.addElement("");  
                                           }
             
           arrContents[0] = "STUDENT";
           arrContents[1] = "Name: " + strCName;
           arrContents[2] = "Surname: " + strCSurName;
           arrContents[3] = "BirthDay: " + strBDay;
           arrContents[4] = "Gender: " + strCGender;
           arrContents[5] = strNKR;
           arrContents[6] = "";
           arrContents[7] = "Day of Enrollment: "+ strEnrolment;
           arrContents[8] = "";
           arrContents[9] = strGorP;
           arrContents[10] = "Name: " + strCName;
           arrContents[11] = "Surname: " + strCSurName;
           arrContents[12] = "BirthDay: " + strGBDay;
           arrContents[13] = "Gender: " + strGGender;
           arrContents[14] = "RelationShip With Child" + strRelation;
           arrContents[15] = "Residential Address: " + strAddress;
           arrContents[16] = "Contact Detials: " + strContact;
           arrContents[17] = strContact2;
           arrContents[18] = "Emergency Contact Details: " + strEmergency;
           
           
           for(int x = 0; x < arrContents.length; x++)
           {
               dlmList.addElement(String.valueOf(arrContents[x]));
           }
           lstKids.setModel(dlmList);
           lblCreate.setText("When you have added all information press save");
           lblOutput.setText(strEnrolment);
             }
         if (boolCheck == false){
            JOptionPane.showMessageDialog(null, "Please Fill in all information before selecting the ADD button");
        }
     
    }//GEN-LAST:event_btnAddActionPerformed

 
    private void spCreateFile()
    {
    String strCName, strCSurName, strTxt, strYear;
    strCName = txtChildName.getText();
    strCSurName = txtChildSurname.getText();
    strYear = cboCYearB.getSelectedItem().toString();    
    strTxt = strCName + strCSurName + strYear + ".txt";
    File Textfile = new File(strTxt);
       try
       {
           Textfile.createNewFile();                     
       }
       catch (Exception Ex)
       {
           JOptionPane.showMessageDialog(null, Ex);
       }
    }                                             
    private void spCreateTxt(){
    String strCName, strCSurName, strTxt, strYear;
    strCName = txtChildName.getText();
    strCSurName = txtChildSurname.getText();
    strYear = cboCYearB.getSelectedItem().toString();    
    strTxt = strCName + strCSurName + strYear + ".txt";
     int intIndex = lstKids.getModel().getSize();
        String[] arrSTR = new String[intIndex];
        for(int i=0; i<intIndex; i++)
        {
            arrSTR[i]=lstKids.getModel().getElementAt(i);
        
        try
        {
            String strfilename=strTxt;
            FileWriter fw = new FileWriter(strfilename,true);
            fw.write(arrSTR[i]+ "\r\n");
            fw.close();
            lblCreate.setText("File has been Saved");
        }
        catch(Exception Ex)
        {
            JOptionPane.showMessageDialog(null, "Text File failed to generate" + Ex);
        }
        }
    }
    
    
    private void btnSaveInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveInformationActionPerformed
    spCreateFile();
    spCreateTxt();       
    }//GEN-LAST:event_btnSaveInformationActionPerformed
   
    
    
    private void rbParentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbParentActionPerformed
     if (rbParent.isSelected())
        {
           rbGuardian.setSelected(false); 
        }
        else if(rbGuardian.isSelected())
        {
           rbParent.setSelected(false); 
        } 
    }//GEN-LAST:event_rbParentActionPerformed

    private void rbGuardianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGuardianActionPerformed
      if (rbGuardian.isSelected())
        {
           rbParent.setSelected(false); 
        }
        else if(rbParent.isSelected())
        {
           rbGuardian.setSelected(false); 
        }
    }//GEN-LAST:event_rbGuardianActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
       dlmList.removeAllElements();
       lblCreate.setText("File has not been saved yet. When you have added all information press save");
       txtAddress.setText(null);
       txtChildName.setText(null);
       txtChildSurname.setText(null);
       txtContact.setText(null);
       txtContact1.setText(null);
       txtEmergency.setText(null);
       txtGName.setText(null);
       txtGSurname.setText(null);
       cboGenderC.setSelectedIndex(0);
       cboGenderG.setSelectedIndex(0);
       cboCDayB.setSelectedIndex(0);
       cboCMonthB.setSelectedIndex(0);
       cboCYearB.setSelectedIndex(0);
       cboDayOld.setSelectedIndex(0);
       cboGYearB.setSelectedIndex(0);
       cboMonthOld.setSelectedIndex(0);
       rbAverage.setSelected(false);
       rbBad.setSelected(false);
       rbGood.setSelected(false);
       rbGuardian.setSelected(false);
       rbParent.setSelected(false);
       lblOutput.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void rbGoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbGoodActionPerformed
        if (rbGood.isSelected())
        {
           rbAverage.setSelected(false); 
           rbBad.setSelected(false);
        }
        else if(rbAverage.isSelected())
        {
           rbGood.setSelected(false);
           rbBad.setSelected(false);
        }else if(rbBad.isSelected())
        {
           rbGood.setSelected(false);
           rbAverage.setSelected(false);
        }
    }//GEN-LAST:event_rbGoodActionPerformed

    private void rbAverageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAverageActionPerformed
       if(rbAverage.isSelected())
        {
           rbGood.setSelected(false);
           rbBad.setSelected(false);
        }
        else if(rbGood.isSelected())
        {
           rbAverage.setSelected(false); 
           rbBad.setSelected(false);
        }
        else if(rbBad.isSelected())
        {
           rbGood.setSelected(false);
           rbAverage.setSelected(false);
        }
    }//GEN-LAST:event_rbAverageActionPerformed

    private void rbBadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBadActionPerformed
        if(rbBad.isSelected())
        {
           rbGood.setSelected(false);
           rbAverage.setSelected(false);
        }
        else if(rbGood.isSelected())
        {
           rbAverage.setSelected(false); 
           rbBad.setSelected(false);
        }
        else if(rbAverage.isSelected())
        {
           rbGood.setSelected(false);
           rbBad.setSelected(false);
        }
    }//GEN-LAST:event_rbBadActionPerformed

    private void txtContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtContactActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Guardian;
    private javax.swing.JLabel ResidentialAddress;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSaveInformation;
    private javax.swing.JComboBox<String> cboCDayB;
    private javax.swing.JComboBox<String> cboCMonthB;
    private javax.swing.JComboBox<String> cboCYearB;
    private javax.swing.JComboBox<String> cboDayOld;
    private javax.swing.JComboBox<String> cboGYearB;
    private javax.swing.JComboBox<String> cboGenderC;
    private javax.swing.JComboBox<String> cboGenderG;
    private javax.swing.JComboBox<String> cboMonthOld;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCreate;
    private javax.swing.JLabel lblOutput;
    private javax.swing.JList<String> lstKids;
    private javax.swing.JRadioButton rbAverage;
    private javax.swing.JRadioButton rbBad;
    private javax.swing.JRadioButton rbGood;
    private javax.swing.JRadioButton rbGuardian;
    private javax.swing.JRadioButton rbParent;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtChildName;
    private javax.swing.JTextField txtChildSurname;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtContact1;
    private javax.swing.JTextField txtEmergency;
    private javax.swing.JTextField txtGName;
    private javax.swing.JTextField txtGSurname;
    // End of variables declaration//GEN-END:variables
}